# Site settings
title: Unf0rG1v3n
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jean Pierre
user_description: I'm a security engineer from Colombia, always trying to protecting environmet in a KISS (Keep It So Simple) way.
user_title: Security Engineer
email: jean.santamaria93@gmail.com
# twitter_username: lorem_ipsum
# facebook_username: user
linkedin_username: jean-santamaria-a1002787
github_username:  jean0828
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
